version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - database:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    links:
      - db
    depends_on:
      - 'db'
    ports:
      - 8000:8080

volumes:
  database:
    driver: local
